// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Reading struct {
	ID         string
	SensorID   string
	Value      float64
	Unit       string
	RecordedAt string
}
