// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package db

import (
	"context"
)

const getReading = `-- name: GetReading :one
SELECT id, sensor_id, value, unit, recorded_at
FROM readings
WHERE id = ?
`

func (q *Queries) GetReading(ctx context.Context, id string) (Reading, error) {
	row := q.db.QueryRowContext(ctx, getReading, id)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.SensorID,
		&i.Value,
		&i.Unit,
		&i.RecordedAt,
	)
	return i, err
}

const insertReading = `-- name: InsertReading :exec
INSERT INTO readings (id, sensor_id, value, unit, recorded_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertReadingParams struct {
	ID         string
	SensorID   string
	Value      float64
	Unit       string
	RecordedAt string
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertReading,
		arg.ID,
		arg.SensorID,
		arg.Value,
		arg.Unit,
		arg.RecordedAt,
	)
	return err
}

const listReadings = `-- name: ListReadings :many
SELECT id, sensor_id, value, unit, recorded_at
FROM readings
ORDER BY recorded_at DESC
`

func (q *Queries) ListReadings(ctx context.Context) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SensorID,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsBySensor = `-- name: ListReadingsBySensor :many
SELECT id, sensor_id, value, unit, recorded_at
FROM readings
WHERE sensor_id = ?
ORDER BY recorded_at ASC, id ASC
`

func (q *Queries) ListReadingsBySensor(ctx context.Context, sensorID string) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadingsBySensor, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SensorID,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
